# Centralized tool versions for CI/CD
# This file defines all tool versions used across the CI pipeline
# Update this file to change versions globally

# Programming languages
python: "3.10"
node: "18"
go: "1.21"
lua: "5.4"
rust: "1.75"

# Build tools
cmake: "3.25.0"
protoc: "3.21.12"

# Python packages
python_packages:
  # Formatters
  black: "24.3.0"
  isort: "5.13.2"
  
  # Linters
  flake8: "7.0.0"
  mypy: "1.8.0"
  pylint: "3.0.3"
  
  # Security
  bandit: "1.7.7"
  safety: "3.0.1"
  
  # Testing
  pytest: "8.0.0"
  pytest-cov: "4.1.0"
  pytest-asyncio: "0.23.5"
  pytest-timeout: "2.2.0"
  
  # Documentation
  sphinx: "7.2.6"
  sphinx-rtd-theme: "2.0.0"
  myst-parser: "2.0.0"

# Lua packages
lua_packages:
  # Formatter
  stylua: "v0.20.0"
  
  # Linter
  luacheck: "1.1.1"
  
  # Testing
  busted: "2.2.0"
  luacov: "0.15.0"

# C++ tools
cpp_tools:
  clang-format: "15"
  clang-tidy: "15"
  cppcheck: "2.13"

# Container tools
container_tools:
  docker: "24.0"
  buildx: "0.12"
  trivy: "0.49"

# Protocol tools
proto_tools:
  buf: "v1.28.1"
  protoc-gen-go: "v1.32.0"
  protoc-gen-python: "latest"

# GitHub Actions versions
github_actions:
  checkout: "v4"
  setup-python: "v5"
  setup-node: "v4"
  setup-go: "v5"
  cache: "v4"
  upload-artifact: "v4"
  download-artifact: "v4"
  docker/setup-buildx-action: "v3"
  docker/build-push-action: "v6"
  docker/login-action: "v3"
  codecov/codecov-action: "v5"

# Timeouts (in seconds)
timeouts:
  default: 300  # 5 minutes
  build: 1200   # 20 minutes
  test: 600     # 10 minutes
  integration: 900  # 15 minutes

# Retry configuration
retry:
  max_attempts: 3
  initial_delay: 5
  backoff_factor: 2
  
# Resource limits
resources:
  min_disk_gb: 10
  min_memory_gb: 4
  max_parallel_jobs: 4