version: '3.8'

services:
  resource-coordinator:
    build:
      context: ../../..
      dockerfile: jimbot/mocks/resource_coordinator/Dockerfile
    container_name: mock-resource-coordinator
    ports:
      - '50051:50051'
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      python -m jimbot.mocks.resource_coordinator.server
      --port 50051
      --mode always_grant
    networks:
      - jimbot-network
    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          "import grpc; channel = grpc.insecure_channel('localhost:50051'); channel.close()",
        ]
      interval: 10s
      timeout: 5s
      retries: 3

  resource-coordinator-ui:
    build:
      context: ../../..
      dockerfile: jimbot/mocks/resource_coordinator/Dockerfile
    container_name: mock-resource-coordinator-ui
    ports:
      - '8080:8080'
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      python -m jimbot.mocks.resource_coordinator.web_ui
      --port 8080
      --coordinator-host resource-coordinator
      --coordinator-port 50051
    depends_on:
      - resource-coordinator
    networks:
      - jimbot-network

networks:
  jimbot-network:
    driver: bridge
