# CI Quick Checks - New unified workflow
name: CI Quick Checks

on:
  push:
    branches: [main, develop, 'feature/**']
  pull_request:
    branches: [main, develop]

jobs:
  quick-checks:
    name: Format and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build CI Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ci-unified
          target: ci
          tags: jimbot-ci:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
          
      - name: Run Quick Checks
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace jimbot-ci:latest bash -c "
            set -e
            echo '=== Python Format Check ==='
            black --check /workspace/jimbot /workspace/scripts /workspace/services
            isort --check-only /workspace/jimbot /workspace/scripts /workspace/services
            
            echo '=== Python Linting ==='
            flake8 /workspace --max-line-length=120 --exclude=.git,__pycache__,venv
            pylint /workspace/jimbot --fail-under=8.0
            mypy /workspace/jimbot --ignore-missing-imports
            
            echo '=== Rust Format Check ==='
            cd /workspace && cargo fmt --all -- --check
            
            echo '=== Rust Linting ==='
            cargo clippy --all-targets --all-features -- -D warnings
            
            echo '=== C++ Linting ==='
            find /workspace -name '*.cpp' -o -name '*.h' | xargs clang-tidy-15
            
            echo '=== Security Audit ==='
            cargo audit
          "