name: Code Quality

# IMPORTANT: Quality checks are temporarily set to continue-on-error
# to unblock CI pipeline. See QUALITY_CHECKS_TODO.md for details
# and re-enabling instructions. Issue: #113

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    continue-on-error: true  # Temporarily disable blocking while we fix quality issues
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -e ".[dev]"

    - name: Run tests with coverage
      run: |
        pytest --cov=jimbot --cov-report=xml --cov-report=term

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  codeclimate:
    name: CodeClimate Analysis
    runs-on: ubuntu-latest
    continue-on-error: true  # Temporarily disable blocking while we fix quality issues
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install -e ".[dev]"

    - name: Run CodeClimate
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: pytest --cov=jimbot --cov-report=xml
        debug: true

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    continue-on-error: true  # Temporarily disable blocking while we fix quality issues
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'python', 'cpp' ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
