name: C++ CI

on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'
  pull_request:
    paths:
      - '**.cpp'
      - '**.h'
      - '**/CMakeLists.txt'

jobs:
  cpp-checks:
    name: C++ Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-15 clang-tidy-15 cppcheck lcov

      - name: Configure CMake
        run: |
          cmake -B build \
            -DCMAKE_C_COMPILER=clang-15 \
            -DCMAKE_CXX_COMPILER=clang++-15 \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DENABLE_COVERAGE=ON

      - name: Run clang-tidy
        run: |
          find . -name "*.cpp" -o -name "*.h" | xargs clang-tidy-15 -p build

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --error-exitcode=1 --project=build/compile_commands.json

      - name: Build
        run: |
          cmake --build build --parallel

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate coverage
        run: |
          lcov --capture --directory build --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.info
          flags: cpp
